# Generated by Django 5.1.6 on 2025-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
