# Generated by Django 5.1.6 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0003_alter_cartitem_unique_together_cart_dishes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='carts', to='Cafe.dish'),
        ),
    ]
