# Generated by Django 5.1.6 on 2025-02-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0004_alter_cart_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='dishes',
            new_name='item',
        ),
    ]
