# Generated by Django 5.1.6 on 2025-02-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0005_rename_dishes_cart_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Item',
        ),
    ]
